### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by paulmurdoch19**
This is part of PEDS-1307, currently amanuensis is installing psycopg2 for userdataportalmodel but since this is the package that needs the library it should be imported here instead. Also bump sqlalchemy to the current version

### CODE REVIEW

**Comment by paulmurdoch19** [comment]
It might also be useful to add some check with github actions to make sure the version in setup.py is up to date before new tags are created

**Comment by grugna** [comment]
@paulmurdoch19 I see the update to the setup.py but I don't see the updates to the requirements or the pipfile. Feel free to migrate this to poetry if you prefer.

Please add the GitHub action. let me know if you need extra permission to do that.

**Comment by paulmurdoch19** [comment]
ok I migrated to poetry and added the github actions

**Comment by paulmurdoch19** [comment]
if you give me admin permissions on this repo we can also add a branch protection that will block any PR into main if the check fails

**Comment by grugna** [comment]
@paulmurdoch19 you are an admin now. I created a branch protection on master a while ago, so that should already be there.

**Comment by paulmurdoch19** [comment]
thanks I cant add it till this gets merged into master, but when it does I will do it

**Comment by grugna** [comment]
new version is 1.7.0

**Pull request merged**
